[tool.pylint.messages_control]
disable = [
  "no-name-in-module",
  "missing-class-docstring",
  "missing-function-docstring",
  "missing-module-docstring",
  "too-few-public-methods",
  "abstract-method",
  "duplicate-code",
]


[tool.pylint]
generated-members = "torch.*"


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q -x --cov"
testpaths = [
    "tests"
]
python_files = "test*.py"
markers = [
  "network: mark a test for all network functionality",
  "geonames: mark a test designed for geonames api",
  "ncbi: mark a test designed for ncbi api",
  "cache: mark a test designed for the cache system"
]
